version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: bma-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=bma_db

  backend:
    build:
      context: .
      dockerfile: cmd/backend/Dockerfile
    container_name: bma-backend
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bma-frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8080
    volumes:
      - ./frontend:/app:delegated
      - /app/node_modules/
    depends_on:
      - backend

volumes:
  mongodb_data: 